// <auto-generated />
using Ch06.Aho.CityInfo.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ch06.Aho.CityInfo.API.Migrations
{
    [DbContext(typeof(AhoCityInfoContext))]
    [Migration("20240602105801_DbAhoCityInfoInitialDataSeeding")]
    partial class DbAhoCityInfoInitialDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Ch06.Aho.CityInfo.API.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Big Apple!",
                            Name = "New York City"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The capital of French gastronomy!",
                            Name = "Lyon"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The place of birth of AHO!",
                            Name = "Jijel"
                        });
                });

            modelBuilder.Entity("Ch06.Aho.CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("PointsOfInterest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Description = "The most visited urban park in the United States!",
                            Name = "Central Park"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Description = "An iconic 102-story skyscraper in Manhattan!",
                            Name = "Empire State Building"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 2,
                            Description = "A beautiful cathedral (late 19th century) that overlooks the city of Lyon from the Fourvière Hill.",
                            Name = "Basilica Notre-Dame de Fourvière"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Description = "A museum of natural history, anthropology, societies, and civilizations, housed in a modern-designed building.",
                            Name = "Confluences Museum"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 3,
                            Description = "Known for its diverse landscapes, including forests, mountains, and beaches.",
                            Name = "Taza National Park"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 3,
                            Description = "An iconic landmark along the shores of Jijel.",
                            Name = "Phare de Ras Afia"
                        });
                });

            modelBuilder.Entity("Ch06.Aho.CityInfo.API.Entities.PointOfInterest", b =>
                {
                    b.HasOne("Ch06.Aho.CityInfo.API.Entities.City", "City")
                        .WithMany("PointsOfInterest")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Ch06.Aho.CityInfo.API.Entities.City", b =>
                {
                    b.Navigation("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
